name: Deploy Files

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Package Android
      run: |
        mkdir -p _site/android
        cp android/checker.html _site/android/
    
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
